service: carts-service

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, "dev"}
  apiGateway:
    shouldStartNameWithService: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'
  environment:
    CARTS_TABLE: carts-table-${self:provider.stage}
    PRODUCTS_TABLE: products-table-${self:provider.stage}
    PRODUCT_DELETED_QUEUE: product-deleted-queue-${self:provider.stage}
    PRODUCT_DELETED_DEAD: dead-product-deleted-queue-${self:provider.stage}
    PRODUCT_EDITED_QUEUE: product-edited-queue-${self:provider.stage}
    PRODUCT_EDITED_DEAD: dead-product-edited-queue-${self:provider.stage}
    PRODUCT_PAYED_QUEUE: product-payed-queue-${self:provider.stage}
    PRODUCT_PAYED_DEAD: dead-product-payed-queue-${self:provider.stage}

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-dynamodb-seed
  - serverless-offline

functions:
  editCart:
    handler: src/endpoints/editCart.handler
    description: New content of the buyer's cart
    events:
      - http:
          path: cart
          method: PATCH
          cors: true
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  getCartToken:
    handler: src/endpoints/getCartToken.handler
    description: Obtain information about a user personal cart
    events:
      - http:
          path: cart
          method: PATCH
          cors: true
          authorizer: 
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

resources:
  Resources:
    ProductEditedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.PRODUCT_EDITED_QUEUE}
        DelaySeconds: 0
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            !GetAtt 'DeadEditedProduct.Arn'

    DeadEditedProduct:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.PRODUCT_EDITED_DEAD}
        MessageRetentionPeriod: 604800 #7 days, should be enough time to fix an issue and retry the messages again in case of a critical issue

    SqsEditedProductPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: ProductEditedQueue
        PolicyDocument:
          Version: "2021-04-19"
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - sqs:SendMessage
              Resource:
                !GetAtt 'ProductEditedQueue.Arn'
              Condition:
                ArnEquals:
                  'aws:SourceArn': arn:aws:sns:eu-west-1:501082649462:ProductEdited.fifo

    ProductEditedTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint:
          !GetAtt 'ProductEditedQueue.Arn'
        Protocol: "sqs"
        TopicArn: arn:aws:sns:eu-west-1:501082649462:ProductEdited.fifo

    ProductPayedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.PRODUCT_PAYED_QUEUE}
        DelaySeconds: 0
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            !GetAtt 'DeadPayedProduct.Arn'

    DeadPayedProduct:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.PRODUCT_PAYED_DEAD}
        MessageRetentionPeriod: 604800 #7 days, should be enough time to fix an issue and retry the messages again in case of a critical issue

    SqsPayedProductPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: ProductPayedQueue
        PolicyDocument:
          Version: "2021-04-19"
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - sqs:SendMessage
              Resource:
                !GetAtt 'ProductPayedQueue.Arn'
              Condition:
                ArnEquals:
                  'aws:SourceArn': arn:aws:sns:eu-west-1:501082649462:ProductPayed.fifo

    ProductPayedTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint:
          !GetAtt 'ProductPayedQueue.Arn'
        Protocol: "sqs"
        TopicArn: arn:aws:sns:eu-west-1:501082649462:ProductPayed.fifo
    
    ProductDeletedQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.environment.PRODUCT_DELETED_QUEUE}
        DelaySeconds: 0
        VisibilityTimeout: 30
        RedrivePolicy:
          deadLetterTargetArn:
            !GetAtt 'DeadBoughtProduct.Arn'

    DeadDeletedProduct:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.environment.PRODUCT_DELETED_DEAD}
        MessageRetentionPeriod: 604800 #7 days, should be enough time to fix an issue and retry the messages again in case of a critical issue

    SqsDeletedProductPolicy:
      Type: AWS::SQS::QueuePolicy
      Properties:
        Queues:
          - Ref: ProductDeletedQueue
        PolicyDocument:
          Version: "2021-04-19"
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - sqs:SendMessage
              Resource:
                !GetAtt 'ProductDeletedQueue.Arn'
              Condition:
                ArnEquals:
                  'aws:SourceArn': arn:aws:sns:eu-west-1:501082649462:ProductDeleted.fifo

    ProductDeletedTopicSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint:
          !GetAtt 'ProductDeletedQueue.Arn'
        Protocol: "sqs"
        TopicArn: arn:aws:sns:eu-west-1:501082649462:ProductDeleted.fifo

    CartsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.CARTS_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    ApiGatewayAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerResultTtlInSeconds: 300
        IdentitySource: method.request.header.Authorization
        Name: Cognito
        RestApiId: 
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS
        ProviderARNs:
          - !GetAtt 'CognitoUserPool.Arn'

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
    migration:
      dir: ./offline
